### ISSUE TITLE
Name change for Kyber, Dilithium and SPHINCS+

### ISSUE THREAD

**Issue by auriee** [tireddy2/pqc-for-engineers#28]
Dear co-authors/contributors/WG members,

I want to open the floor for discussion and decision to change from Kyber, Dilithium, and SPHINCS+ to ML-KEM,ML-DSA and SLH-DSA respectively in the PQC for Engineers document.

Please respond with your valued feedback and reasons.

@tireddy2 @Dimitris-Schoinianakis @timfromdigicert @ounsworth @kriskwiatkowski 

Regards,
Aritra.

**Comment by kriskwiatkowski** [comment]
@auriee  That makes sense to me to change naming. I'm guessing names that follow FIPS naming convention will be more widely used and hence we should refer to new names in the document.
By analogy, most widely used block cipher is known as AES rather than Rijndael.

PS: Personally I much more prefer "Kyber/Dilithium/SPHINCS" than MLKEM/ML...

**Comment by auriee** [comment]
@kriskwiatkowski Thank you for the feedback, that makes a lot of sense, indeed we don't say Rijndael but AES is the norm.

I'll wait for the feedback of other authors/contributors/WG members and lets see if we have a consensus.
